spring:
  application:
    name: springboot-data-redis-demo

  redis:
    database: 0
    host: 192.168.1.11
    password: youdian
    port: 16379
    lettuce:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 20
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 20
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 5
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0

server:
  port: 8081

